/**
 * Demo dataset: every entity in at least one of every state.
 *
 * Run with:
 *   bun --env-file=.env.localrun packages/db/src/seed-demo.ts
 *
 * Idempotent: every row it owns uses a stable `demo_`/`user_`/`client_`/`project_`
 * style id, and the script deletes the rows it owns before re-inserting.
 */
import { hashPassword } from "better-auth/crypto";
import { inArray, sql as raw } from "drizzle-orm";
import {
  accounts,
  activityEvents,
  agencies,
  approvals,
  attachments,
  auditLogs,
  channelReads,
  channels,
  checklistItems,
  checklists,
  clients,
  comments,
  customFieldDefs,
  customFieldValues,
  db,
  deliverablePlacements,
  deliverables,
  dependencies,
  fileVersions,
  formFields,
  formSubmissions,
  intakeForms,
  messages,
  milestones,
  notifications,
  pipelineStageApprovers,
  pipelineStages,
  pipelines,
  projectMembers,
  projects,
  recurringSchedules,
  reviewRuns,
  reviewStageApprovers,
  reviewStages,
  rules,
  savedViews,
  shares,
  sql,
  tasks,
  templatePacks,
  uploadSessions,
  users,
} from "./index";

const MEDIA = process.env.DEMO_MEDIA_BASE_URL ?? "http://localhost:5173/demo";
const AGENCY = "agency_trex";
const PASSWORD = "rexops-demo";

const day = 24 * 60 * 60 * 1000;
const now = Date.now();
const ago = (days: number) => new Date(now - days * day);
const ahead = (days: number) => new Date(now + days * day);

const perm = (over: Record<string, boolean> = {}) => ({
  canApprove: false,
  canInviteClients: false,
  canManageTeam: false,
  canUploadFinal: false,
  canViewAllClients: false,
  canManageAutomations: false,
  ...over,
});

// ---------------------------------------------------------------- identities

const agencyUsers = [
  {
    id: "user_manas",
    name: "Manas Rao",
    email: "manas@trex.test",
    role: "AGENCY_OWNER",
    specialty: "GENERAL",
    permissions: perm({
      canApprove: true,
      canInviteClients: true,
      canManageTeam: true,
      canUploadFinal: true,
      canViewAllClients: true,
      canManageAutomations: true,
    }),
  },
  {
    id: "user_arjun",
    name: "Arjun Mehta",
    email: "arjun@trex.test",
    role: "AGENCY_ADMIN",
    specialty: "PM",
    permissions: perm({
      canApprove: true,
      canInviteClients: true,
      canManageTeam: true,
      canUploadFinal: true,
      canViewAllClients: true,
      canManageAutomations: true,
    }),
  },
  {
    id: "user_riya",
    name: "Riya Kapoor",
    email: "riya@trex.test",
    role: "AGENCY_MEMBER",
    specialty: "MOTION",
    permissions: perm({ canUploadFinal: true }),
  },
  {
    id: "user_neha",
    name: "Neha Iyer",
    email: "neha@trex.test",
    role: "AGENCY_MEMBER",
    specialty: "DESIGNER",
    permissions: perm(),
  },
  {
    id: "user_dev",
    name: "Dev Sharma",
    email: "dev@trex.test",
    role: "AGENCY_MEMBER",
    specialty: "PHOTOGRAPHER",
    permissions: perm(),
  },
  {
    id: "user_tara",
    name: "Tara Nair",
    email: "tara@trex.test",
    role: "AGENCY_MEMBER",
    specialty: "ACCOUNT",
    permissions: perm({ canInviteClients: true, canViewAllClients: true }),
  },
  {
    id: "user_vikram",
    name: "Vikram Bose",
    email: "vikram@trex.test",
    role: "AGENCY_MEMBER",
    specialty: "EDITOR",
    permissions: perm(),
    banned: true,
    banReason: "Contract ended — access suspended",
  },
] as const;

const clientRows = [
  {
    id: "client_imperial",
    name: "Imperial Living",
    companyName: "Imperial Living Pvt Ltd",
    email: "sara@imperial.test",
    phone: "+91 98200 11221",
    website: "https://imperial.test",
    notes: "Flagship retainer. Two approvers, Sara signs off.",
    status: "ACTIVE",
    portalSlug: "imperial-living",
  },
  {
    id: "client_nova",
    name: "Nova Fitness",
    companyName: "Nova Fitness Collective",
    email: "priya@nova.test",
    phone: "+91 98111 44553",
    website: "https://novafitness.test",
    notes: "Launch campaign, fast turnaround expected.",
    status: "ACTIVE",
    portalSlug: "nova-fitness",
  },
  {
    id: "client_latitude",
    name: "Latitude Coffee",
    companyName: "Latitude Coffee Roasters",
    email: "meera@latitude.test",
    phone: "+91 90040 88112",
    notes: "Paused after the spring menu drop.",
    status: "INACTIVE",
    portalSlug: "latitude-coffee",
  },
  {
    id: "client_harbour",
    name: "Old Harbour Co",
    companyName: "Old Harbour Trading Co",
    email: "ops@oldharbour.test",
    notes: "Wrapped in 2024. Kept for archive access.",
    status: "ARCHIVED",
    portalSlug: "old-harbour",
  },
] as const;

const clientUsers = [
  {
    id: "user_sara",
    name: "Sara Fernandes",
    email: "sara@imperial.test",
    clientId: "client_imperial",
    role: "CLIENT_OWNER",
    permissions: perm({ canApprove: true, canInviteClients: true }),
  },
  {
    id: "user_rahul",
    name: "Rahul Menon",
    email: "rahul@imperial.test",
    clientId: "client_imperial",
    role: "CLIENT_MEMBER",
    permissions: perm(),
  },
  {
    id: "user_priya",
    name: "Priya Deshmukh",
    email: "priya@nova.test",
    clientId: "client_nova",
    role: "CLIENT_OWNER",
    permissions: perm({ canApprove: true, canInviteClients: true }),
  },
  {
    id: "user_karan",
    name: "Karan Shetty",
    email: "karan@nova.test",
    clientId: "client_nova",
    role: "CLIENT_MEMBER",
    permissions: perm(),
  },
  {
    id: "user_meera",
    name: "Meera Joshi",
    email: "meera@latitude.test",
    clientId: "client_latitude",
    role: "CLIENT_OWNER",
    permissions: perm({ canApprove: true }),
  },
] as const;

// ------------------------------------------------------------------ projects

const projectRows = [
  {
    id: "project_june_retainer",
    clientId: "client_imperial",
    name: "June Content Retainer",
    type: "Social Media Retainer",
    status: "IN_PROGRESS",
    priority: "HIGH",
    description: "Always-on social for Imperial Living: 12 reels + 16 statics a month.",
    brief: "Warm, editorial, people-first. No stock. Always shoot in golden hour.",
    startDate: ago(24),
    dueDate: ahead(9),
  },
  {
    id: "project_reels",
    clientId: "client_imperial",
    parentProjectId: "project_june_retainer",
    name: "Reels",
    status: "IN_PROGRESS",
    priority: "HIGH",
    description: "Short-form vertical cuts.",
    startDate: ago(24),
    dueDate: ahead(9),
  },
  {
    id: "project_statics",
    clientId: "client_imperial",
    parentProjectId: "project_june_retainer",
    name: "Statics & Carousels",
    status: "ACTIVE",
    priority: "MEDIUM",
    description: "Feed statics and multi-slide carousels.",
    startDate: ago(20),
    dueDate: ahead(14),
  },
  {
    id: "project_q3_launch",
    clientId: "client_imperial",
    name: "Q3 Collection Launch",
    type: "Campaign",
    status: "WAITING_FOR_CLIENT",
    priority: "URGENT",
    description: "Hero film, brand board and launch deck for the Q3 collection.",
    brief: "Hero film must land under 45s. Deck goes to their board on the 30th.",
    startDate: ago(30),
    dueDate: ahead(3),
  },
  {
    id: "project_brandkit",
    clientId: "client_imperial",
    name: "Brand Kit Refresh",
    type: "Brand",
    status: "COMPLETED",
    priority: "MEDIUM",
    description: "Logo lockups, type scale and a launch film. Delivered and signed off.",
    startDate: ago(120),
    dueDate: ago(35),
  },
  {
    id: "project_2024_archive",
    clientId: "client_imperial",
    name: "2024 Always-On (Archive)",
    type: "Social Media Retainer",
    status: "ARCHIVED",
    priority: "LOW",
    description: "Closed retainer, kept for reference.",
    startDate: ago(420),
    dueDate: ago(120),
  },
  {
    id: "project_nova_launch",
    clientId: "client_nova",
    name: "Nova Studio Launch",
    type: "Campaign",
    status: "ACTIVE",
    priority: "HIGH",
    description: "Opening week campaign for the Bandra studio.",
    brief: "High energy, hard cuts, lots of sweat. 9:16 only.",
    startDate: ago(11),
    dueDate: ahead(6),
  },
  {
    id: "project_nova_draft",
    clientId: "client_nova",
    name: "Q4 Membership Push",
    type: "Campaign",
    status: "DRAFT",
    priority: "LOW",
    description: "Not scoped yet — waiting on their budget confirmation.",
  },
  {
    id: "project_latitude_menu",
    clientId: "client_latitude",
    name: "Spring Menu Drop",
    type: "Content Sprint",
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    description: "Menu statics and a single hero shot.",
    startDate: ago(45),
    dueDate: ago(2),
  },
  {
    id: "project_harbour_wrap",
    clientId: "client_harbour",
    name: "Harbour Wrap-Up",
    status: "ARCHIVED",
    priority: "LOW",
    description: "Final handover pack.",
    startDate: ago(500),
    dueDate: ago(400),
  },
] as const;

// -------------------------------------------------------------- deliverables

const deliverableRows = [
  {
    id: "deliverable_beach_vibe",
    projectId: "project_reels",
    clientId: "client_imperial",
    title: "Beach Vibe Reel",
    description: "30s vertical cut for the June drop. Licensed track, no VO.",
    contentType: "MOTION",
    status: "IN_PROGRESS",
    priority: "HIGH",
    assignedToUserId: "user_riya",
    dueDate: ahead(2),
    agencyNote: "Waiting on the colour pass before it goes to internal.",
  },
  {
    id: "deliverable_sunset_carousel",
    projectId: "project_statics",
    clientId: "client_imperial",
    title: "Sunset Carousel (5 slides)",
    description: "Five-slide carousel built off the rooftop shoot.",
    contentType: "STATIC",
    status: "PENDING",
    priority: "MEDIUM",
    assignedToUserId: "user_neha",
    dueDate: ahead(7),
  },
  {
    id: "deliverable_menu_static",
    projectId: "project_latitude_menu",
    clientId: "client_latitude",
    title: "Spring Menu Static",
    description: "Feed static announcing the new menu.",
    contentType: "STATIC",
    status: "READY_FOR_INTERNAL_REVIEW",
    priority: "MEDIUM",
    assignedToUserId: "user_neha",
    dueDate: ago(1),
  },
  {
    id: "deliverable_brand_board",
    projectId: "project_q3_launch",
    clientId: "client_imperial",
    title: "Q3 Brand Board",
    description: "Colour, type and art-direction board for the Q3 collection.",
    contentType: "STATIC",
    status: "UNDER_INTERNAL_REVIEW",
    priority: "URGENT",
    assignedToUserId: "user_neha",
    dueDate: ahead(1),
    submittedAt: ago(1),
  },
  {
    id: "deliverable_founder_portrait",
    projectId: "project_q3_launch",
    clientId: "client_imperial",
    title: "Founder Portrait Set",
    description: "Six retouched portraits for the press kit.",
    contentType: "STATIC",
    status: "INTERNAL_APPROVED",
    priority: "HIGH",
    assignedToUserId: "user_dev",
    dueDate: ahead(4),
    submittedAt: ago(3),
    reviewedAt: ago(2),
  },
  {
    id: "deliverable_gym_launch",
    projectId: "project_nova_launch",
    clientId: "client_nova",
    title: "Studio Launch Film",
    description: "Hero 9:16 launch film for opening week.",
    contentType: "MOTION",
    status: "UNDER_CLIENT_REVIEW",
    priority: "URGENT",
    assignedToUserId: "user_riya",
    dueDate: ahead(1),
    submittedAt: ago(1),
  },
  {
    id: "deliverable_holiday_teaser",
    projectId: "project_reels",
    clientId: "client_imperial",
    title: "Holiday Teaser",
    description: "15s teaser for the holiday capsule.",
    contentType: "MOTION",
    status: "REVISION_REQUESTED",
    priority: "HIGH",
    assignedToUserId: "user_riya",
    dueDate: ago(1),
    submittedAt: ago(4),
    reviewedAt: ago(2),
    clientNote: "Love the energy, but the logo end-card is on screen far too long.",
  },
  {
    id: "deliverable_q3_deck",
    projectId: "project_q3_launch",
    clientId: "client_imperial",
    title: "Q3 Campaign Deck",
    description: "Board-facing deck. PDF, 18 pages.",
    contentType: "OTHER",
    status: "APPROVED",
    priority: "HIGH",
    assignedToUserId: "user_arjun",
    dueDate: ahead(5),
    submittedAt: ago(6),
    reviewedAt: ago(5),
    approvedAt: ago(5),
  },
  {
    id: "deliverable_launch_film",
    projectId: "project_brandkit",
    clientId: "client_imperial",
    title: "Brand Launch Film",
    description: "60s brand film. Delivered in 4K + social crops.",
    contentType: "MOTION",
    status: "DELIVERED",
    priority: "MEDIUM",
    assignedToUserId: "user_riya",
    dueDate: ago(40),
    submittedAt: ago(45),
    reviewedAt: ago(42),
    approvedAt: ago(41),
  },
  {
    id: "deliverable_legacy_banner",
    projectId: "project_2024_archive",
    clientId: "client_imperial",
    title: "2024 Diwali Banner",
    description: "Archived from the closed retainer.",
    contentType: "STATIC",
    status: "ARCHIVED",
    priority: "LOW",
    assignedToUserId: "user_neha",
    dueDate: ago(300),
    approvedAt: ago(290),
  },
  {
    id: "deliverable_nova_statics",
    projectId: "project_nova_launch",
    clientId: "client_nova",
    title: "Opening Week Statics",
    description: "Six feed statics for opening week.",
    contentType: "STATIC",
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    assignedToUserId: "user_neha",
    dueDate: ahead(3),
  },
  {
    id: "deliverable_nova_trailer",
    projectId: "project_nova_launch",
    clientId: "client_nova",
    title: "Coach Intro Cutdowns",
    description: "Three 10s cutdowns, one per coach.",
    contentType: "MOTION",
    status: "READY_FOR_INTERNAL_REVIEW",
    priority: "MEDIUM",
    assignedToUserId: "user_riya",
    dueDate: ago(2),
  },
  {
    id: "deliverable_rooftop_still",
    projectId: "project_statics",
    clientId: "client_imperial",
    title: "Rooftop Hero Still",
    description: "Hero still from the rooftop shoot, sized for the feed and the site banner.",
    contentType: "STATIC",
    status: "UNDER_CLIENT_REVIEW",
    priority: "HIGH",
    assignedToUserId: "user_dev",
    dueDate: ahead(2),
    submittedAt: ago(1),
  },
  {
    id: "deliverable_harbour_pack",
    projectId: "project_harbour_wrap",
    clientId: "client_harbour",
    title: "Final Handover Pack",
    contentType: "OTHER",
    status: "DELIVERED",
    priority: "LOW",
    assignedToUserId: "user_arjun",
    dueDate: ago(400),
    approvedAt: ago(400),
  },
] as const;

// -------------------------------------------------------------- file versions

type VersionSeed = {
  id: string;
  deliverableId: string;
  versionNumber: number;
  major: number;
  minor: number;
  label: string;
  tags?: string[];
  status: string;
  visibility: "INTERNAL" | "CLIENT";
  uploadedBy: string;
  createdAt: Date;
  media: string;
  motion?: { durationMs: number; spriteRows: number };
  kind?: "image" | "video" | "pdf";
  sizeMb: number;
};

const versionRows: VersionSeed[] = [
  {
    id: "fv_beach_v1",
    deliverableId: "deliverable_beach_vibe",
    versionNumber: 1,
    major: 1,
    minor: 0,
    label: "First assembly",
    tags: ["rough-cut"],
    status: "REPLACED",
    visibility: "INTERNAL",
    uploadedBy: "user_riya",
    createdAt: ago(9),
    media: "beach-vibe-v1",
    kind: "image",
    sizeMb: 42,
  },
  {
    id: "fv_beach_v2",
    deliverableId: "deliverable_beach_vibe",
    versionNumber: 2,
    major: 2,
    minor: 0,
    label: "Music swap",
    tags: ["rough-cut", "audio"],
    status: "REPLACED",
    visibility: "INTERNAL",
    uploadedBy: "user_riya",
    createdAt: ago(5),
    media: "beach-vibe-v2",
    kind: "image",
    sizeMb: 48,
  },
  {
    id: "fv_beach_v3",
    deliverableId: "deliverable_beach_vibe",
    versionNumber: 3,
    major: 2,
    minor: 1,
    label: "Colour pass",
    tags: ["colour"],
    status: "UPLOADED",
    visibility: "INTERNAL",
    uploadedBy: "user_riya",
    createdAt: ago(1),
    media: "beach-vibe-v3-motion",
    kind: "video",
    motion: { durationMs: 12_000, spriteRows: 3 },
    sizeMb: 61,
  },
  {
    id: "fv_menu_v1",
    deliverableId: "deliverable_menu_static",
    versionNumber: 1,
    major: 1,
    minor: 0,
    label: "Menu static",
    status: "UPLOADED",
    visibility: "INTERNAL",
    uploadedBy: "user_neha",
    createdAt: ago(3),
    media: "menu-static",
    kind: "image",
    sizeMb: 8,
  },
  {
    id: "fv_board_v1",
    deliverableId: "deliverable_brand_board",
    versionNumber: 1,
    major: 1,
    minor: 0,
    label: "Board v1",
    tags: ["art-direction"],
    status: "UNDER_INTERNAL_REVIEW",
    visibility: "INTERNAL",
    uploadedBy: "user_neha",
    createdAt: ago(1),
    media: "brand-board",
    kind: "image",
    sizeMb: 14,
  },
  {
    id: "fv_portrait_v1",
    deliverableId: "deliverable_founder_portrait",
    versionNumber: 1,
    major: 1,
    minor: 0,
    label: "Retouch pass 1",
    status: "INTERNAL_APPROVED",
    visibility: "INTERNAL",
    uploadedBy: "user_dev",
    createdAt: ago(3),
    media: "founder-portrait",
    kind: "image",
    sizeMb: 27,
  },
  {
    id: "fv_gym_v1",
    deliverableId: "deliverable_gym_launch",
    versionNumber: 1,
    major: 1,
    minor: 0,
    label: "Client cut",
    tags: ["hero"],
    status: "UNDER_CLIENT_REVIEW",
    visibility: "CLIENT",
    uploadedBy: "user_riya",
    createdAt: ago(1),
    media: "gym-launch-motion",
    kind: "video",
    motion: { durationMs: 10_000, spriteRows: 2 },
    sizeMb: 88,
  },
  {
    id: "fv_holiday_v1",
    deliverableId: "deliverable_holiday_teaser",
    versionNumber: 1,
    major: 1,
    minor: 0,
    label: "Teaser cut",
    status: "CHANGES_REQUESTED",
    visibility: "CLIENT",
    uploadedBy: "user_riya",
    createdAt: ago(4),
    media: "holiday-teaser-motion",
    kind: "video",
    motion: { durationMs: 15_000, spriteRows: 3 },
    sizeMb: 54,
  },
  {
    id: "fv_deck_v1",
    deliverableId: "deliverable_q3_deck",
    versionNumber: 1,
    major: 1,
    minor: 0,
    label: "Board deck",
    status: "APPROVED",
    visibility: "CLIENT",
    uploadedBy: "user_arjun",
    createdAt: ago(6),
    media: "brand-guidelines",
    kind: "pdf",
    sizeMb: 6,
  },
  {
    id: "fv_launchfilm_v1",
    deliverableId: "deliverable_launch_film",
    versionNumber: 1,
    major: 1,
    minor: 0,
    label: "Final master",
    tags: ["final", "4k"],
    status: "APPROVED",
    visibility: "CLIENT",
    uploadedBy: "user_riya",
    createdAt: ago(45),
    media: "holiday-teaser-motion",
    kind: "video",
    motion: { durationMs: 15_000, spriteRows: 3 },
    sizeMb: 1240,
  },
  {
    id: "fv_novatrailer_v1",
    deliverableId: "deliverable_nova_trailer",
    versionNumber: 1,
    major: 1,
    minor: 0,
    label: "Coach cutdowns",
    status: "UPLOADED",
    visibility: "INTERNAL",
    uploadedBy: "user_riya",
    createdAt: ago(2),
    media: "gym-launch-motion",
    kind: "video",
    motion: { durationMs: 10_000, spriteRows: 2 },
    sizeMb: 33,
  },
  {
    id: "fv_rooftop_v1",
    deliverableId: "deliverable_rooftop_still",
    versionNumber: 1,
    major: 1,
    minor: 0,
    label: "Graded still",
    tags: ["hero"],
    status: "UNDER_CLIENT_REVIEW",
    visibility: "CLIENT",
    uploadedBy: "user_dev",
    createdAt: ago(1),
    media: "sunset-carousel",
    kind: "image",
    sizeMb: 19,
  },
  {
    id: "fv_legacy_v1",
    deliverableId: "deliverable_legacy_banner",
    versionNumber: 1,
    major: 1,
    minor: 0,
    label: "Archived master",
    status: "APPROVED",
    visibility: "CLIENT",
    uploadedBy: "user_neha",
    createdAt: ago(300),
    media: "sunset-carousel",
    kind: "image",
    sizeMb: 11,
  },
];

function versionValues(v: VersionSeed) {
  const isVideo = v.kind === "video";
  const isPdf = v.kind === "pdf";
  const ext = isVideo ? "mp4" : isPdf ? "pdf" : "jpg";
  const preview = isVideo ? `${MEDIA}/${v.media}.mp4` : `${MEDIA}/${v.media}.${ext}`;
  return {
    id: v.id,
    agencyId: AGENCY,
    deliverableId: v.deliverableId,
    versionNumber: v.versionNumber,
    majorVersion: v.major,
    minorVersion: v.minor,
    versionBump: (v.minor === 0 ? "MAJOR" : "MINOR") as "MAJOR" | "MINOR",
    isMinor: v.minor !== 0,
    label: v.label,
    tags: v.tags ?? [],
    fileUrl: preview,
    previewUrl: preview,
    posterFrameUrl: isVideo ? `${MEDIA}/${v.media}-poster.jpg` : null,
    thumbnailSpriteUrl: isVideo ? `${MEDIA}/${v.media}-sprite.jpg` : null,
    spriteIntervalMs: isVideo ? 1000 : null,
    spriteColumns: isVideo ? 5 : null,
    spriteRows: isVideo ? (v.motion?.spriteRows ?? 3) : null,
    spriteCellWidth: isVideo ? 160 : null,
    spriteCellHeight: isVideo ? 284 : null,
    durationMs: isVideo ? (v.motion?.durationMs ?? null) : null,
    previewStatus: "READY" as const,
    previewGeneratedAt: v.createdAt,
    fileName: `${v.media}.${ext}`,
    fileType: isVideo ? "video/mp4" : isPdf ? "application/pdf" : "image/jpeg",
    fileSizeBytes: BigInt(Math.round(v.sizeMb * 1024 * 1024)),
    isSource: false,
    visibility: v.visibility,
    status: v.status as never,
    uploadedByUserId: v.uploadedBy,
    createdAt: v.createdAt,
    updatedAt: v.createdAt,
  };
}

// ------------------------------------------------------------------ teardown

const ownedProjects = projectRows.map((p) => p.id);
const ownedDeliverables = deliverableRows.map((d) => d.id);
const ownedClients = clientRows.map((c) => c.id);
const ownedUsers = [...agencyUsers.map((u) => u.id), ...clientUsers.map((u) => u.id)];

async function wipe() {
  // Ordered child → parent. `demo_` prefixed rows plus the canonical ids we own.
  const stmts = [
    raw`delete from comment_reaction where comment_id like 'demo_%'`,
    // `approval` carries a trigger that makes rows immutable; a demo re-seed has to
    // step around it, so lift the trigger for the duration of the delete only.
    raw`alter table approval disable trigger user`,
    raw`delete from approval where agency_id = ${AGENCY}`,
    raw`alter table approval enable trigger user`,
    raw`delete from review_stage_approver where agency_id = ${AGENCY}`,
    raw`delete from review_stage where agency_id = ${AGENCY}`,
    raw`delete from review_run where agency_id = ${AGENCY}`,
    raw`delete from comment where agency_id = ${AGENCY}`,
    raw`delete from checklist_item where agency_id = ${AGENCY}`,
    raw`delete from checklist where agency_id = ${AGENCY}`,
    raw`delete from dependency where agency_id = ${AGENCY}`,
    raw`delete from channel_read where agency_id = ${AGENCY}`,
    raw`delete from message where agency_id = ${AGENCY}`,
    raw`delete from channel where agency_id = ${AGENCY}`,
    raw`delete from attachment where agency_id = ${AGENCY}`,
    raw`delete from notification where agency_id = ${AGENCY}`,
    raw`delete from activity_event where agency_id = ${AGENCY}`,
    raw`delete from share where agency_id = ${AGENCY}`,
    raw`delete from upload_session where agency_id = ${AGENCY}`,
    raw`delete from custom_field_value where agency_id = ${AGENCY}`,
    raw`delete from saved_view where agency_id = ${AGENCY}`,
    raw`delete from form_submission where agency_id = ${AGENCY}`,
    raw`delete from form_field where agency_id = ${AGENCY}`,
    raw`delete from intake_form where agency_id = ${AGENCY}`,
    raw`delete from recurring_schedule where agency_id = ${AGENCY}`,
    raw`delete from template_pack where agency_id = ${AGENCY}`,
    raw`delete from rule where agency_id = ${AGENCY}`,
    raw`delete from audit_log where agency_id = ${AGENCY}`,
    raw`delete from outbox where agency_id = ${AGENCY}`,
    raw`delete from task where agency_id = ${AGENCY}`,
    raw`delete from milestone where agency_id = ${AGENCY}`,
    raw`delete from file_version where agency_id = ${AGENCY}`,
    raw`delete from deliverable_placement where agency_id = ${AGENCY}`,
    raw`delete from deliverable where agency_id = ${AGENCY}`,
    raw`delete from project_member where agency_id = ${AGENCY}`,
    raw`delete from project where agency_id = ${AGENCY}`,
    raw`delete from pipeline_stage_approver where agency_id = ${AGENCY}`,
    raw`delete from pipeline_stage where agency_id = ${AGENCY}`,
    raw`delete from pipeline where agency_id = ${AGENCY}`,
    raw`delete from custom_field_def where agency_id = ${AGENCY}`,
    raw`delete from push_subscription where agency_id = ${AGENCY}`,
  ];
  for (const stmt of stmts) await db.execute(stmt);
  // Users/clients last, and only the ones this script owns.
  await db.execute(
    raw`delete from session where user_id in (select id from "user" where agency_id = ${AGENCY})`,
  );
  await db.execute(
    raw`delete from account where user_id in (select id from "user" where agency_id = ${AGENCY})`,
  );
  await db.execute(raw`delete from client where agency_id = ${AGENCY}`);
  await db.execute(raw`delete from "user" where agency_id = ${AGENCY}`);
}

// ---------------------------------------------------------------------- seed

async function seed() {
  await wipe();

  await db
    .insert(agencies)
    .values({
      id: AGENCY,
      name: "T-Rex Media",
      slug: "t-rex-media",
      brandColor: "#F2A341",
      settings: { storageQuotaBytes: 100 * 1024 ** 3 },
    })
    .onConflictDoUpdate({
      target: agencies.id,
      set: { name: "T-Rex Media", settings: { storageQuotaBytes: 100 * 1024 ** 3 } },
    });

  await db.insert(users).values(
    agencyUsers.map((u) => ({
      id: u.id,
      name: u.name,
      email: u.email,
      emailVerified: true,
      role: u.role as never,
      specialty: u.specialty as never,
      agencyId: AGENCY,
      permissions: u.permissions,
      banned: "banned" in u ? (u.banned as boolean) : false,
      banReason: "banReason" in u ? (u.banReason as string) : null,
    })),
  );

  await db.insert(clients).values(
    clientRows.map((c) => ({
      id: c.id,
      agencyId: AGENCY,
      name: c.name,
      companyName: c.companyName,
      email: c.email,
      phone: "phone" in c ? (c.phone as string) : null,
      website: "website" in c ? (c.website as string) : null,
      notes: c.notes,
      status: c.status as never,
      portalSlug: c.portalSlug,
      createdByUserId: "user_manas",
    })),
  );

  await db.insert(users).values(
    clientUsers.map((u) => ({
      id: u.id,
      name: u.name,
      email: u.email,
      emailVerified: true,
      role: u.role as never,
      agencyId: AGENCY,
      clientId: u.clientId,
      permissions: u.permissions,
    })),
  );

  await db.insert(projects).values(
    projectRows.map((p) => ({
      id: p.id,
      agencyId: AGENCY,
      clientId: p.clientId,
      parentProjectId: "parentProjectId" in p ? (p.parentProjectId as string) : null,
      name: p.name,
      description: p.description ?? null,
      brief: "brief" in p ? (p.brief as string) : null,
      type: "type" in p ? (p.type as string) : null,
      status: p.status as never,
      priority: p.priority as never,
      startDate: "startDate" in p ? (p.startDate as Date) : null,
      dueDate: "dueDate" in p ? (p.dueDate as Date) : null,
      createdByUserId: "user_manas",
    })),
  );

  const memberships: Array<[string, string, string]> = [
    ["project_june_retainer", "user_manas", "lead"],
    ["project_june_retainer", "user_arjun", "producer"],
    ["project_june_retainer", "user_tara", "account"],
    ["project_reels", "user_riya", "editor"],
    ["project_reels", "user_arjun", "producer"],
    ["project_statics", "user_neha", "designer"],
    ["project_q3_launch", "user_manas", "lead"],
    ["project_q3_launch", "user_neha", "designer"],
    ["project_q3_launch", "user_dev", "photographer"],
    ["project_q3_launch", "user_arjun", "producer"],
    ["project_brandkit", "user_riya", "editor"],
    ["project_brandkit", "user_manas", "lead"],
    ["project_nova_launch", "user_riya", "editor"],
    ["project_nova_launch", "user_neha", "designer"],
    ["project_nova_launch", "user_tara", "account"],
    ["project_nova_draft", "user_tara", "account"],
    ["project_latitude_menu", "user_neha", "designer"],
    ["project_2024_archive", "user_neha", "designer"],
    ["project_harbour_wrap", "user_arjun", "producer"],
  ];
  await db.insert(projectMembers).values(
    memberships.map(([projectId, userId, roleOnProject]) => ({
      agencyId: AGENCY,
      projectId,
      userId,
      roleOnProject,
    })),
  );

  await db.insert(deliverables).values(
    deliverableRows.map((d) => ({
      id: d.id,
      agencyId: AGENCY,
      clientId: d.clientId,
      projectId: d.projectId,
      contentType: d.contentType as never,
      title: d.title,
      description: "description" in d ? (d.description as string) : null,
      status: d.status as never,
      priority: d.priority as never,
      assignedToUserId: d.assignedToUserId,
      dueDate: d.dueDate,
      agencyNote: "agencyNote" in d ? (d.agencyNote as string) : null,
      clientNote: "clientNote" in d ? (d.clientNote as string) : null,
      submittedAt: "submittedAt" in d ? (d.submittedAt as Date) : null,
      reviewedAt: "reviewedAt" in d ? (d.reviewedAt as Date) : null,
      approvedAt: "approvedAt" in d ? (d.approvedAt as Date) : null,
      createdByUserId: "user_arjun",
    })),
  );

  await db.insert(deliverablePlacements).values(
    deliverableRows.map((d) => ({
      agencyId: AGENCY,
      deliverableId: d.id,
      projectId: d.projectId,
    })),
  );

  await db.insert(fileVersions).values(versionRows.map(versionValues));

  // ------------------------------------------------------------- pipelines
  await db.insert(pipelines).values([
    {
      id: "pipeline_default",
      agencyId: AGENCY,
      name: "Default internal → client",
      isDefault: true,
    },
    {
      id: "pipeline_fast",
      agencyId: AGENCY,
      name: "Fast track (client only)",
      projectType: "Campaign",
      isDefault: false,
    },
  ]);
  await db.insert(pipelineStages).values([
    {
      id: "pstage_internal",
      agencyId: AGENCY,
      pipelineId: "pipeline_default",
      name: "Internal review",
      type: "INTERNAL",
      mode: "SEQUENTIAL",
      sequence: 1,
      requiresInternalApproval: true,
      slaHours: 24,
      requiredCount: 1,
      escalateToUserId: "user_manas",
    },
    {
      id: "pstage_client",
      agencyId: AGENCY,
      pipelineId: "pipeline_default",
      name: "Client review",
      type: "CLIENT",
      mode: "SEQUENTIAL",
      sequence: 2,
      requiresClientApproval: true,
      slaHours: 48,
      requiredCount: 1,
    },
    {
      id: "pstage_fast_client",
      agencyId: AGENCY,
      pipelineId: "pipeline_fast",
      name: "Client sign-off",
      type: "CLIENT",
      mode: "PARALLEL",
      sequence: 1,
      requiresClientApproval: true,
      requiredCount: 2,
      slaHours: 12,
    },
  ]);
  await db.insert(pipelineStageApprovers).values([
    { agencyId: AGENCY, pipelineStageId: "pstage_internal", userId: "user_manas" },
    { agencyId: AGENCY, pipelineStageId: "pstage_internal", userId: "user_arjun" },
    { agencyId: AGENCY, pipelineStageId: "pstage_client", userId: "user_sara" },
    { agencyId: AGENCY, pipelineStageId: "pstage_fast_client", userId: "user_priya" },
    {
      agencyId: AGENCY,
      pipelineStageId: "pstage_fast_client",
      userId: "user_karan",
      approverOrder: 2,
      required: false,
    },
  ]);

  // ----------------------------------------------------------- review runs
  await db.insert(reviewRuns).values([
    {
      id: "run_board",
      agencyId: AGENCY,
      deliverableId: "deliverable_brand_board",
      fileVersionId: "fv_board_v1",
      pipelineId: "pipeline_default",
      pipelineName: "Default internal → client",
      status: "INTERNAL_REVIEW",
      startedAt: ago(1),
      createdByUserId: "user_neha",
      createdAt: ago(1),
    },
    {
      id: "run_portrait",
      agencyId: AGENCY,
      deliverableId: "deliverable_founder_portrait",
      fileVersionId: "fv_portrait_v1",
      pipelineId: "pipeline_default",
      pipelineName: "Default internal → client",
      status: "INTERNAL_APPROVED",
      startedAt: ago(3),
      createdByUserId: "user_dev",
      createdAt: ago(3),
    },
    {
      id: "run_gym",
      agencyId: AGENCY,
      deliverableId: "deliverable_gym_launch",
      fileVersionId: "fv_gym_v1",
      pipelineId: "pipeline_fast",
      pipelineName: "Fast track (client only)",
      status: "CLIENT_REVIEW",
      startedAt: ago(1),
      createdByUserId: "user_riya",
      createdAt: ago(1),
    },
    {
      id: "run_deck",
      agencyId: AGENCY,
      deliverableId: "deliverable_q3_deck",
      fileVersionId: "fv_deck_v1",
      pipelineId: "pipeline_default",
      pipelineName: "Default internal → client",
      status: "APPROVED",
      startedAt: ago(6),
      completedAt: ago(5),
      createdByUserId: "user_arjun",
      createdAt: ago(6),
    },
    {
      id: "run_rooftop",
      agencyId: AGENCY,
      deliverableId: "deliverable_rooftop_still",
      fileVersionId: "fv_rooftop_v1",
      pipelineId: "pipeline_default",
      pipelineName: "Default internal → client",
      status: "CLIENT_REVIEW",
      startedAt: ago(2),
      createdByUserId: "user_dev",
      createdAt: ago(2),
    },
    {
      id: "run_holiday",
      agencyId: AGENCY,
      deliverableId: "deliverable_holiday_teaser",
      fileVersionId: "fv_holiday_v1",
      pipelineId: "pipeline_default",
      pipelineName: "Default internal → client",
      status: "REJECTED",
      startedAt: ago(4),
      completedAt: ago(2),
      createdByUserId: "user_riya",
      createdAt: ago(4),
    },
    {
      id: "run_launchfilm",
      agencyId: AGENCY,
      deliverableId: "deliverable_launch_film",
      fileVersionId: "fv_launchfilm_v1",
      pipelineId: "pipeline_default",
      pipelineName: "Default internal → client",
      status: "APPROVED",
      startedAt: ago(45),
      completedAt: ago(41),
      createdByUserId: "user_riya",
      createdAt: ago(45),
    },
  ]);

  await db.insert(reviewStages).values([
    // brand board: internal ACTIVE, client PENDING
    {
      id: "rs_board_internal",
      agencyId: AGENCY,
      deliverableId: "deliverable_brand_board",
      reviewRunId: "run_board",
      pipelineStageId: "pstage_internal",
      name: "Internal review",
      type: "INTERNAL",
      order: 1,
      requiredCount: 1,
      slaHours: 24,
      escalateToUserId: "user_manas",
      status: "ACTIVE",
      activatedAt: ago(1),
      dueAt: ahead(0.2),
    },
    {
      id: "rs_board_client",
      agencyId: AGENCY,
      deliverableId: "deliverable_brand_board",
      reviewRunId: "run_board",
      pipelineStageId: "pstage_client",
      name: "Client review",
      type: "CLIENT",
      order: 2,
      requiredCount: 1,
      slaHours: 48,
      status: "PENDING",
    },
    // portrait: internal PASSED, client PENDING
    {
      id: "rs_portrait_internal",
      agencyId: AGENCY,
      deliverableId: "deliverable_founder_portrait",
      reviewRunId: "run_portrait",
      pipelineStageId: "pstage_internal",
      name: "Internal review",
      type: "INTERNAL",
      order: 1,
      status: "PASSED",
      activatedAt: ago(3),
      completedAt: ago(2),
    },
    {
      id: "rs_portrait_client",
      agencyId: AGENCY,
      deliverableId: "deliverable_founder_portrait",
      reviewRunId: "run_portrait",
      pipelineStageId: "pstage_client",
      name: "Client review",
      type: "CLIENT",
      order: 2,
      status: "PENDING",
    },
    // gym: parallel client stage ACTIVE, 2 approvers
    {
      id: "rs_gym_client",
      agencyId: AGENCY,
      deliverableId: "deliverable_gym_launch",
      reviewRunId: "run_gym",
      pipelineStageId: "pstage_fast_client",
      name: "Client sign-off",
      type: "CLIENT",
      mode: "PARALLEL",
      order: 1,
      requiredCount: 2,
      slaHours: 12,
      status: "ACTIVE",
      activatedAt: ago(1),
      dueAt: ahead(0.1),
    },
    // deck: both PASSED
    {
      id: "rs_deck_internal",
      agencyId: AGENCY,
      deliverableId: "deliverable_q3_deck",
      reviewRunId: "run_deck",
      pipelineStageId: "pstage_internal",
      name: "Internal review",
      type: "INTERNAL",
      order: 1,
      status: "PASSED",
      activatedAt: ago(6),
      completedAt: ago(6),
    },
    {
      id: "rs_deck_client",
      agencyId: AGENCY,
      deliverableId: "deliverable_q3_deck",
      reviewRunId: "run_deck",
      pipelineStageId: "pstage_client",
      name: "Client review",
      type: "CLIENT",
      order: 2,
      status: "PASSED",
      activatedAt: ago(6),
      completedAt: ago(5),
    },
    // rooftop still: internal PASSED, client stage ACTIVE and waiting on Sara
    {
      id: "rs_rooftop_internal",
      agencyId: AGENCY,
      deliverableId: "deliverable_rooftop_still",
      reviewRunId: "run_rooftop",
      pipelineStageId: "pstage_internal",
      name: "Internal review",
      type: "INTERNAL",
      order: 1,
      status: "PASSED",
      activatedAt: ago(2),
      completedAt: ago(1),
    },
    {
      id: "rs_rooftop_client",
      agencyId: AGENCY,
      deliverableId: "deliverable_rooftop_still",
      reviewRunId: "run_rooftop",
      pipelineStageId: "pstage_client",
      name: "Client review",
      type: "CLIENT",
      order: 2,
      requiredCount: 1,
      slaHours: 48,
      status: "ACTIVE",
      activatedAt: ago(1),
      dueAt: ahead(1),
    },
    // holiday: internal PASSED, client REJECTED
    {
      id: "rs_holiday_internal",
      agencyId: AGENCY,
      deliverableId: "deliverable_holiday_teaser",
      reviewRunId: "run_holiday",
      pipelineStageId: "pstage_internal",
      name: "Internal review",
      type: "INTERNAL",
      order: 1,
      status: "PASSED",
      activatedAt: ago(4),
      completedAt: ago(4),
    },
    {
      id: "rs_holiday_client",
      agencyId: AGENCY,
      deliverableId: "deliverable_holiday_teaser",
      reviewRunId: "run_holiday",
      pipelineStageId: "pstage_client",
      name: "Client review",
      type: "CLIENT",
      order: 2,
      status: "REJECTED",
      activatedAt: ago(3),
      completedAt: ago(2),
    },
    {
      id: "rs_launchfilm_internal",
      agencyId: AGENCY,
      deliverableId: "deliverable_launch_film",
      reviewRunId: "run_launchfilm",
      pipelineStageId: "pstage_internal",
      name: "Internal review",
      type: "INTERNAL",
      order: 1,
      status: "PASSED",
      activatedAt: ago(45),
      completedAt: ago(44),
    },
    {
      id: "rs_launchfilm_client",
      agencyId: AGENCY,
      deliverableId: "deliverable_launch_film",
      reviewRunId: "run_launchfilm",
      pipelineStageId: "pstage_client",
      name: "Client review",
      type: "CLIENT",
      order: 2,
      status: "PASSED",
      activatedAt: ago(44),
      completedAt: ago(41),
    },
  ]);

  await db.insert(reviewStageApprovers).values([
    { agencyId: AGENCY, reviewStageId: "rs_board_internal", userId: "user_manas" },
    { agencyId: AGENCY, reviewStageId: "rs_board_internal", userId: "user_arjun" },
    { agencyId: AGENCY, reviewStageId: "rs_board_client", userId: "user_sara" },
    { agencyId: AGENCY, reviewStageId: "rs_portrait_internal", userId: "user_manas" },
    { agencyId: AGENCY, reviewStageId: "rs_portrait_client", userId: "user_sara" },
    { agencyId: AGENCY, reviewStageId: "rs_gym_client", userId: "user_priya" },
    {
      agencyId: AGENCY,
      reviewStageId: "rs_gym_client",
      userId: "user_karan",
      approverOrder: 2,
      required: false,
    },
    { agencyId: AGENCY, reviewStageId: "rs_deck_internal", userId: "user_manas" },
    { agencyId: AGENCY, reviewStageId: "rs_deck_client", userId: "user_sara" },
    { agencyId: AGENCY, reviewStageId: "rs_rooftop_internal", userId: "user_manas" },
    { agencyId: AGENCY, reviewStageId: "rs_rooftop_client", userId: "user_sara" },
    { agencyId: AGENCY, reviewStageId: "rs_holiday_internal", userId: "user_arjun" },
    { agencyId: AGENCY, reviewStageId: "rs_holiday_client", userId: "user_sara" },
    { agencyId: AGENCY, reviewStageId: "rs_launchfilm_internal", userId: "user_manas" },
    { agencyId: AGENCY, reviewStageId: "rs_launchfilm_client", userId: "user_sara" },
  ]);

  await db.insert(approvals).values([
    {
      id: "demo_ap_portrait",
      agencyId: AGENCY,
      deliverableId: "deliverable_founder_portrait",
      fileVersionId: "fv_portrait_v1",
      reviewStageId: "rs_portrait_internal",
      reviewRunId: "run_portrait",
      decidedByUserId: "user_manas",
      decision: "APPROVE",
      feedback: "Retouch is clean. Push it to Sara.",
      decidedAt: ago(2),
      createdAt: ago(2),
    },
    {
      id: "demo_ap_deck_internal",
      agencyId: AGENCY,
      deliverableId: "deliverable_q3_deck",
      fileVersionId: "fv_deck_v1",
      reviewStageId: "rs_deck_internal",
      reviewRunId: "run_deck",
      decidedByUserId: "user_manas",
      decision: "APPROVE",
      feedback: "Numbers check out.",
      decidedAt: ago(6),
      createdAt: ago(6),
    },
    {
      id: "demo_ap_deck_client",
      agencyId: AGENCY,
      deliverableId: "deliverable_q3_deck",
      fileVersionId: "fv_deck_v1",
      reviewStageId: "rs_deck_client",
      reviewRunId: "run_deck",
      decidedByUserId: "user_sara",
      decision: "APPROVE",
      feedback: "Approved for the board meeting.",
      eSignature: "Sara Fernandes",
      signatureConsentText: "I approve this deliverable on behalf of Imperial Living.",
      signatureConsentVersion: "v1",
      requestIp: "203.0.113.44",
      requestUserAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
      decidedAt: ago(5),
      createdAt: ago(5),
    },
    {
      id: "demo_ap_holiday",
      agencyId: AGENCY,
      deliverableId: "deliverable_holiday_teaser",
      fileVersionId: "fv_holiday_v1",
      reviewStageId: "rs_holiday_client",
      reviewRunId: "run_holiday",
      decidedByUserId: "user_sara",
      decision: "REQUEST_CHANGES",
      feedback: "End-card holds too long — trim to 1.5s and we're good.",
      decidedAt: ago(2),
      createdAt: ago(2),
    },
    {
      id: "demo_ap_launchfilm_internal",
      agencyId: AGENCY,
      deliverableId: "deliverable_launch_film",
      fileVersionId: "fv_launchfilm_v1",
      reviewStageId: "rs_launchfilm_internal",
      reviewRunId: "run_launchfilm",
      decidedByUserId: "user_manas",
      decision: "APPROVE",
      decidedAt: ago(44),
      createdAt: ago(44),
    },
    {
      id: "demo_ap_launchfilm_client",
      agencyId: AGENCY,
      deliverableId: "deliverable_launch_film",
      fileVersionId: "fv_launchfilm_v1",
      reviewStageId: "rs_launchfilm_client",
      reviewRunId: "run_launchfilm",
      decidedByUserId: "user_sara",
      decision: "APPROVE",
      feedback: "Beautiful. Ship it.",
      eSignature: "Sara Fernandes",
      decidedAt: ago(41),
      createdAt: ago(41),
    },
  ]);

  // -------------------------------------------------------------- comments
  await db.insert(comments).values([
    {
      id: "demo_c_beach_1",
      agencyId: AGENCY,
      deliverableId: "deliverable_beach_vibe",
      fileVersionId: "fv_beach_v3",
      userId: "user_arjun",
      message: "The cut at 0:04 is a frame early — it clips the wave.",
      visibility: "INTERNAL",
      anchorType: "TIMECODE",
      anchor: { timeMs: 4200 },
      mentionUserIds: ["user_riya"],
      reactions: { "👀": ["user_riya"] },
      createdAt: ago(1),
      updatedAt: ago(1),
    },
    {
      id: "demo_c_beach_2",
      agencyId: AGENCY,
      deliverableId: "deliverable_beach_vibe",
      fileVersionId: "fv_beach_v3",
      parentId: "demo_c_beach_1",
      userId: "user_riya",
      message: "Nudged two frames later. Will be in v2.2.",
      visibility: "INTERNAL",
      anchorType: "NONE",
      createdAt: ago(0.6),
      updatedAt: ago(0.6),
    },
    {
      id: "demo_c_beach_3",
      agencyId: AGENCY,
      deliverableId: "deliverable_beach_vibe",
      fileVersionId: "fv_beach_v2",
      userId: "user_manas",
      message: "Track choice is right. Locking it.",
      visibility: "INTERNAL",
      anchorType: "NONE",
      resolvedAt: ago(4),
      resolvedByUserId: "user_manas",
      createdAt: ago(5),
      updatedAt: ago(4),
    },
    {
      id: "demo_c_gym_1",
      agencyId: AGENCY,
      deliverableId: "deliverable_gym_launch",
      fileVersionId: "fv_gym_v1",
      userId: "user_priya",
      message: "Can we hold on the studio wide shot a beat longer? Feels rushed.",
      visibility: "CLIENT_VISIBLE",
      anchorType: "TIMECODE",
      anchor: { timeMs: 6500 },
      createdAt: ago(0.8),
      updatedAt: ago(0.8),
    },
    {
      id: "demo_c_gym_2",
      agencyId: AGENCY,
      deliverableId: "deliverable_gym_launch",
      fileVersionId: "fv_gym_v1",
      parentId: "demo_c_gym_1",
      userId: "user_riya",
      message: "Yes — I can add ~12 frames without breaking the beat.",
      visibility: "CLIENT_VISIBLE",
      anchorType: "NONE",
      createdAt: ago(0.5),
      updatedAt: ago(0.5),
    },
    {
      id: "demo_c_gym_3",
      agencyId: AGENCY,
      deliverableId: "deliverable_gym_launch",
      fileVersionId: "fv_gym_v1",
      userId: "user_karan",
      message: "Logo on the wall is slightly out of focus at the end.",
      visibility: "CLIENT_VISIBLE",
      anchorType: "REGION",
      anchor: { x: 0.62, y: 0.18, width: 0.24, height: 0.14, timeMs: 9200 },
      createdAt: ago(0.4),
      updatedAt: ago(0.4),
    },
    {
      id: "demo_c_board_1",
      agencyId: AGENCY,
      deliverableId: "deliverable_brand_board",
      fileVersionId: "fv_board_v1",
      userId: "user_manas",
      message: "Type scale is off — the H2 and H3 are too close.",
      visibility: "INTERNAL",
      anchorType: "REGION",
      anchor: { x: 0.1, y: 0.42, width: 0.35, height: 0.2 },
      mentionUserIds: ["user_neha"],
      hashtags: ["typography"],
      createdAt: ago(0.9),
      updatedAt: ago(0.9),
    },
    {
      id: "demo_c_holiday_1",
      agencyId: AGENCY,
      deliverableId: "deliverable_holiday_teaser",
      fileVersionId: "fv_holiday_v1",
      userId: "user_sara",
      message: "End-card holds too long. Trim to about 1.5 seconds.",
      visibility: "CLIENT_VISIBLE",
      anchorType: "TIMECODE",
      anchor: { timeMs: 13_200 },
      createdAt: ago(2),
      updatedAt: ago(2),
    },
    {
      id: "demo_c_rooftop_1",
      agencyId: AGENCY,
      deliverableId: "deliverable_rooftop_still",
      fileVersionId: "fv_rooftop_v1",
      userId: "user_dev",
      message: "Graded warmer than the batch — matches the rooftop reference Sara sent.",
      visibility: "CLIENT_VISIBLE",
      anchorType: "NONE",
      createdAt: ago(1),
      updatedAt: ago(1),
    },
    {
      id: "demo_c_menu_1",
      agencyId: AGENCY,
      deliverableId: "deliverable_menu_static",
      fileVersionId: "fv_menu_v1",
      userId: "user_neha",
      message: "Ready for internal — prices are from the final menu PDF.",
      visibility: "INTERNAL",
      anchorType: "NONE",
      createdAt: ago(3),
      updatedAt: ago(3),
    },
  ]);

  // ----------------------------------------------------------------- tasks
  await db.insert(tasks).values([
    {
      id: "demo_t_1",
      agencyId: AGENCY,
      projectId: "project_reels",
      deliverableId: "deliverable_beach_vibe",
      title: "Colour pass on the drone shots",
      status: "IN_PROGRESS",
      assignedToUserId: "user_riya",
      dueDate: ahead(1),
      position: 0,
      taskType: "edit",
      createdByUserId: "user_arjun",
    },
    {
      id: "demo_t_2",
      agencyId: AGENCY,
      projectId: "project_reels",
      deliverableId: "deliverable_beach_vibe",
      title: "Clear the music licence",
      status: "DONE",
      assignedToUserId: "user_tara",
      dueDate: ago(3),
      position: 1,
      taskType: "admin",
      createdByUserId: "user_arjun",
    },
    {
      id: "demo_t_3",
      agencyId: AGENCY,
      projectId: "project_q3_launch",
      deliverableId: "deliverable_brand_board",
      title: "Fix the type scale",
      status: "TODO",
      assignedToUserId: "user_neha",
      dueDate: ahead(1),
      position: 0,
      createdByUserId: "user_manas",
    },
    {
      id: "demo_t_4",
      agencyId: AGENCY,
      projectId: "project_q3_launch",
      title: "Book the studio for the reshoot",
      status: "BLOCKED",
      assignedToUserId: "user_dev",
      dueDate: ago(1),
      position: 1,
      createdByUserId: "user_arjun",
    },
    {
      id: "demo_t_5",
      agencyId: AGENCY,
      projectId: "project_nova_launch",
      deliverableId: "deliverable_nova_statics",
      title: "Lay out the six feed statics",
      status: "IN_PROGRESS",
      assignedToUserId: "user_neha",
      dueDate: ahead(2),
      position: 0,
      createdByUserId: "user_tara",
    },
    {
      id: "demo_t_6",
      agencyId: AGENCY,
      projectId: "project_nova_launch",
      deliverableId: "deliverable_nova_trailer",
      title: "Sync coach VO",
      status: "TODO",
      assignedToUserId: "user_riya",
      dueDate: ahead(3),
      position: 1,
      createdByUserId: "user_tara",
    },
    {
      id: "demo_t_7",
      agencyId: AGENCY,
      projectId: "project_latitude_menu",
      title: "Chase Meera for the final prices",
      status: "BLOCKED",
      assignedToUserId: "user_tara",
      dueDate: ago(5),
      position: 0,
      createdByUserId: "user_arjun",
    },
    {
      id: "demo_t_8",
      agencyId: AGENCY,
      projectId: "project_brandkit",
      title: "Archive the project files",
      status: "DONE",
      assignedToUserId: "user_riya",
      dueDate: ago(34),
      position: 0,
      createdByUserId: "user_manas",
    },
  ]);

  // ------------------------------------------------------------ checklists
  await db.insert(checklists).values([
    {
      id: "demo_cl_beach",
      agencyId: AGENCY,
      deliverableId: "deliverable_beach_vibe",
      title: "Delivery checklist",
      position: 0,
    },
    {
      id: "demo_cl_gym",
      agencyId: AGENCY,
      deliverableId: "deliverable_gym_launch",
      title: "QC before client",
      position: 0,
    },
  ]);
  await db.insert(checklistItems).values([
    {
      agencyId: AGENCY,
      checklistId: "demo_cl_beach",
      text: "Safe-area check for captions",
      done: true,
      assignedToUserId: "user_riya",
      position: 0,
    },
    {
      agencyId: AGENCY,
      checklistId: "demo_cl_beach",
      text: "Loudness normalised to -14 LUFS",
      done: true,
      assignedToUserId: "user_riya",
      position: 1,
    },
    {
      agencyId: AGENCY,
      checklistId: "demo_cl_beach",
      text: "Colour pass signed off",
      done: false,
      assignedToUserId: "user_manas",
      dueDate: ahead(1),
      position: 2,
    },
    {
      agencyId: AGENCY,
      checklistId: "demo_cl_beach",
      text: "Export 9:16 + 1:1 crops",
      done: false,
      position: 3,
    },
    {
      agencyId: AGENCY,
      checklistId: "demo_cl_gym",
      text: "Logo lockup matches brand kit",
      done: true,
      position: 0,
    },
    {
      agencyId: AGENCY,
      checklistId: "demo_cl_gym",
      text: "Music licence attached",
      done: false,
      assignedToUserId: "user_tara",
      position: 1,
    },
  ]);

  // ------------------------------------------------------------ milestones
  await db.insert(milestones).values([
    {
      agencyId: AGENCY,
      projectId: "project_june_retainer",
      name: "June batch 1 delivered",
      dueDate: ago(10),
      reachedAt: ago(10),
    },
    {
      agencyId: AGENCY,
      projectId: "project_june_retainer",
      name: "June batch 2 delivered",
      dueDate: ahead(9),
    },
    {
      agencyId: AGENCY,
      projectId: "project_q3_launch",
      name: "Board presentation",
      dueDate: ahead(3),
    },
    {
      agencyId: AGENCY,
      projectId: "project_nova_launch",
      name: "Opening day",
      dueDate: ahead(6),
    },
    {
      agencyId: AGENCY,
      projectId: "project_brandkit",
      name: "Brand kit handover",
      dueDate: ago(35),
      reachedAt: ago(35),
    },
  ]);

  await db.insert(dependencies).values([
    {
      agencyId: AGENCY,
      fromDeliverableId: "deliverable_brand_board",
      toDeliverableId: "deliverable_q3_deck",
      type: "FS",
    },
    {
      agencyId: AGENCY,
      fromDeliverableId: "deliverable_founder_portrait",
      toDeliverableId: "deliverable_q3_deck",
      type: "FS",
    },
    {
      agencyId: AGENCY,
      fromDeliverableId: "deliverable_nova_statics",
      toDeliverableId: "deliverable_nova_trailer",
      type: "SS",
    },
  ]);

  // ------------------------------------------------------------- channels
  await db.insert(channels).values([
    {
      id: "demo_ch_june",
      agencyId: AGENCY,
      scopeType: "PROJECT",
      scopeId: "project_june_retainer",
      name: "June Content Retainer",
    },
    {
      id: "demo_ch_beach",
      agencyId: AGENCY,
      scopeType: "DELIVERABLE",
      scopeId: "deliverable_beach_vibe",
      name: "Beach Vibe Reel",
    },
    {
      id: "demo_ch_nova",
      agencyId: AGENCY,
      scopeType: "PROJECT",
      scopeId: "project_nova_launch",
      name: "Nova Studio Launch",
    },
  ]);
  await db.insert(messages).values([
    {
      id: "demo_m_1",
      agencyId: AGENCY,
      channelId: "demo_ch_june",
      userId: "user_arjun",
      body: "Batch 2 is due in nine days — three reels and eight statics left.",
      createdAt: ago(2),
      updatedAt: ago(2),
    },
    {
      id: "demo_m_2",
      agencyId: AGENCY,
      channelId: "demo_ch_june",
      userId: "user_riya",
      body: "Beach Vibe goes to internal tomorrow once the colour pass lands.",
      mentionUserIds: ["user_arjun"],
      createdAt: ago(1),
      updatedAt: ago(1),
    },
    {
      id: "demo_m_3",
      agencyId: AGENCY,
      channelId: "demo_ch_june",
      userId: "user_manas",
      parentId: "demo_m_2",
      body: "Good. Flag it to me the moment it's up.",
      createdAt: ago(0.9),
      updatedAt: ago(0.9),
    },
    {
      id: "demo_m_4",
      agencyId: AGENCY,
      channelId: "demo_ch_beach",
      userId: "user_riya",
      body: "v2.1 uploaded with the colour pass.",
      refVersionIds: ["fv_beach_v3"],
      createdAt: ago(1),
      updatedAt: ago(1),
    },
    {
      id: "demo_m_5",
      agencyId: AGENCY,
      channelId: "demo_ch_nova",
      userId: "user_tara",
      body: "Priya wants the film locked before Friday. Karan is the second approver.",
      hashtags: ["urgent"],
      createdAt: ago(1.5),
      updatedAt: ago(1.5),
    },
  ]);
  await db.insert(channelReads).values([
    {
      agencyId: AGENCY,
      channelId: "demo_ch_june",
      userId: "user_manas",
      lastReadMessageId: "demo_m_3",
      readAt: ago(0.8),
    },
    {
      agencyId: AGENCY,
      channelId: "demo_ch_june",
      userId: "user_riya",
      lastReadMessageId: "demo_m_2",
      readAt: ago(1),
    },
  ]);

  // ---------------------------------------------------------------- shares
  await db.insert(shares).values([
    {
      id: "demo_sh_gym",
      agencyId: AGENCY,
      resourceType: "DELIVERABLE",
      resourceId: "deliverable_gym_launch",
      token: "novalaunchpreview",
      allowComment: true,
      allowDownload: false,
      watermark: "STANDARD",
      audience: "CLIENT",
      viewCount: 14,
      expiresAt: ahead(7),
      createdByUserId: "user_tara",
    },
    {
      id: "demo_sh_deck",
      agencyId: AGENCY,
      resourceType: "FILE_VERSION",
      resourceId: "fv_deck_v1",
      token: "q3deckboardcopy",
      allowComment: false,
      allowDownload: true,
      watermark: "FORENSIC",
      audience: "GUEST",
      viewCount: 3,
      createdByUserId: "user_arjun",
    },
    {
      id: "demo_sh_expired",
      agencyId: AGENCY,
      resourceType: "PROJECT",
      resourceId: "project_brandkit",
      token: "brandkitwrapexpired",
      allowComment: false,
      allowDownload: false,
      watermark: "NONE",
      audience: "INTERNAL",
      viewCount: 41,
      expiresAt: ago(10),
      createdByUserId: "user_manas",
    },
  ]);

  // --------------------------------------------------------- activity feed
  const activity: Array<[string, string, string, string, string, string, Date]> = [
    [
      "DELIVERABLE",
      "deliverable_beach_vibe",
      "UPLOAD",
      "user_riya",
      "Riya uploaded v2.1 — Colour pass",
      "INTERNAL",
      ago(1),
    ],
    [
      "DELIVERABLE",
      "deliverable_beach_vibe",
      "COMMENT",
      "user_arjun",
      "Arjun commented at 0:04",
      "INTERNAL",
      ago(1),
    ],
    [
      "DELIVERABLE",
      "deliverable_brand_board",
      "STAGE_CHANGE",
      "user_neha",
      "Sent to internal review",
      "INTERNAL",
      ago(1),
    ],
    [
      "DELIVERABLE",
      "deliverable_gym_launch",
      "STAGE_CHANGE",
      "user_riya",
      "Submitted to client review",
      "CLIENT_VISIBLE",
      ago(1),
    ],
    [
      "DELIVERABLE",
      "deliverable_gym_launch",
      "COMMENT",
      "user_priya",
      "Priya left a note at 0:06",
      "CLIENT_VISIBLE",
      ago(0.8),
    ],
    [
      "DELIVERABLE",
      "deliverable_holiday_teaser",
      "APPROVAL",
      "user_sara",
      "Sara requested changes",
      "CLIENT_VISIBLE",
      ago(2),
    ],
    [
      "DELIVERABLE",
      "deliverable_q3_deck",
      "APPROVAL",
      "user_sara",
      "Sara approved the Q3 deck",
      "CLIENT_VISIBLE",
      ago(5),
    ],
    [
      "DELIVERABLE",
      "deliverable_founder_portrait",
      "APPROVAL",
      "user_manas",
      "Manas approved internally",
      "INTERNAL",
      ago(2),
    ],
    [
      "PROJECT",
      "project_nova_launch",
      "ASSIGNMENT",
      "user_tara",
      "Tara assigned Riya to the launch film",
      "INTERNAL",
      ago(3),
    ],
    [
      "DELIVERABLE",
      "deliverable_launch_film",
      "SHARE",
      "user_manas",
      "Delivered to Imperial Living",
      "CLIENT_VISIBLE",
      ago(41),
    ],
    [
      "DELIVERABLE",
      "deliverable_menu_static",
      "STATUS_CHANGE",
      "user_neha",
      "Marked ready for internal review",
      "INTERNAL",
      ago(3),
    ],
  ];
  await db.insert(activityEvents).values(
    activity.map(([subjectType, subjectId, type, actor, summary, visibility, createdAt], i) => ({
      id: `demo_ae_${i}`,
      agencyId: AGENCY,
      subjectType: subjectType as never,
      subjectId,
      type: type as never,
      actorUserId: actor,
      summary,
      visibility: visibility as never,
      sourceEventId: `demo_ae_src_${i}`,
      createdAt,
    })),
  );

  // -------------------------------------------------------- notifications
  const notify: Array<{
    to: string;
    type: string;
    title: string;
    message: string;
    url: string;
    read: boolean;
    at: Date;
    deliverableId?: string;
    projectId?: string;
  }> = [
    {
      to: "user_manas",
      type: "INTERNAL_REVIEW_REQUESTED",
      title: "Q3 Brand Board needs your review",
      message: "Neha sent v1 to internal review.",
      url: "/agency/review/deliverable_brand_board",
      read: false,
      at: ago(1),
      deliverableId: "deliverable_brand_board",
    },
    {
      to: "user_manas",
      type: "STAGE_STALLED",
      title: "Spring Menu Static is stalled",
      message: "Ready for internal review for 3 days with no reviewer.",
      url: "/agency/review/deliverable_menu_static",
      read: false,
      at: ago(0.5),
      deliverableId: "deliverable_menu_static",
    },
    {
      to: "user_manas",
      type: "APPROVED",
      title: "Sara approved the Q3 Campaign Deck",
      message: "Signed off with an e-signature.",
      url: "/agency/deliverables/deliverable_q3_deck",
      read: true,
      at: ago(5),
      deliverableId: "deliverable_q3_deck",
    },
    {
      to: "user_riya",
      type: "COMMENT_ADDED",
      title: "Arjun commented on Beach Vibe Reel",
      message: "The cut at 0:04 is a frame early.",
      url: "/agency/review/deliverable_beach_vibe",
      read: false,
      at: ago(1),
      deliverableId: "deliverable_beach_vibe",
    },
    {
      to: "user_riya",
      type: "MENTION",
      title: "You were mentioned in June Content Retainer",
      message: "Manas: Flag it to me the moment it's up.",
      url: "/agency/inbox",
      read: false,
      at: ago(0.9),
      projectId: "project_june_retainer",
    },
    {
      to: "user_riya",
      type: "REVISION_REQUESTED",
      title: "Holiday Teaser needs changes",
      message: "End-card holds too long — trim to 1.5s.",
      url: "/agency/review/deliverable_holiday_teaser",
      read: true,
      at: ago(2),
      deliverableId: "deliverable_holiday_teaser",
    },
    {
      to: "user_riya",
      type: "DUE_DATE_REMINDER",
      title: "Beach Vibe Reel is due in 2 days",
      message: "June Content Retainer · Reels",
      url: "/agency/deliverables/deliverable_beach_vibe",
      read: false,
      at: ago(0.2),
      deliverableId: "deliverable_beach_vibe",
    },
    {
      to: "user_neha",
      type: "MENTION",
      title: "Manas mentioned you on Q3 Brand Board",
      message: "Type scale is off — the H2 and H3 are too close.",
      url: "/agency/review/deliverable_brand_board",
      read: false,
      at: ago(0.9),
      deliverableId: "deliverable_brand_board",
    },
    {
      to: "user_neha",
      type: "ASSIGNMENT",
      title: "You were assigned Opening Week Statics",
      message: "Nova Studio Launch · due in 3 days",
      url: "/agency/deliverables/deliverable_nova_statics",
      read: true,
      at: ago(4),
      deliverableId: "deliverable_nova_statics",
    },
    {
      to: "user_arjun",
      type: "VERSION_UPLOADED",
      title: "Riya uploaded v2.1 of Beach Vibe Reel",
      message: "Colour pass",
      url: "/agency/review/deliverable_beach_vibe",
      read: false,
      at: ago(1),
      deliverableId: "deliverable_beach_vibe",
    },
    {
      to: "user_arjun",
      type: "PROJECT_CREATED",
      title: "Q4 Membership Push created",
      message: "Nova Fitness · draft",
      url: "/agency/projects/project_nova_draft",
      read: true,
      at: ago(6),
      projectId: "project_nova_draft",
    },
    {
      to: "user_sara",
      type: "SUBMITTED_TO_CLIENT",
      title: "Founder Portrait Set is coming your way",
      message: "Internally approved, client review opens shortly.",
      url: "/client/review",
      read: false,
      at: ago(2),
      deliverableId: "deliverable_founder_portrait",
    },
    {
      to: "user_sara",
      type: "SUBMITTED_TO_CLIENT",
      title: "Rooftop Hero Still needs your decision",
      message: "Client review opened yesterday · due tomorrow.",
      url: "/client/review/deliverable_rooftop_still",
      read: false,
      at: ago(1),
      deliverableId: "deliverable_rooftop_still",
    },
    {
      to: "user_sara",
      type: "DELIVERED",
      title: "Brand Launch Film delivered",
      message: "Final master + social crops are in your approved folder.",
      url: "/client/approved",
      read: true,
      at: ago(41),
      deliverableId: "deliverable_launch_film",
    },
    {
      to: "user_sara",
      type: "COMMENT_ADDED",
      title: "Riya replied on Holiday Teaser",
      message: "Trimming the end-card now.",
      url: "/client/review/deliverable_holiday_teaser",
      read: false,
      at: ago(1.8),
      deliverableId: "deliverable_holiday_teaser",
    },
    {
      to: "user_priya",
      type: "SUBMITTED_TO_CLIENT",
      title: "Studio Launch Film is ready for your review",
      message: "Two approvals needed — you and Karan.",
      url: "/client/review/deliverable_gym_launch",
      read: false,
      at: ago(1),
      deliverableId: "deliverable_gym_launch",
    },
    {
      to: "user_karan",
      type: "SUBMITTED_TO_CLIENT",
      title: "Studio Launch Film needs your sign-off",
      message: "Parallel approval — Priya has not decided yet.",
      url: "/client/review/deliverable_gym_launch",
      read: false,
      at: ago(1),
      deliverableId: "deliverable_gym_launch",
    },
    {
      to: "user_tara",
      type: "SHARE_VIEWED",
      title: "The Nova preview link was opened",
      message: "14 views since you shared it.",
      url: "/agency/deliverables/deliverable_gym_launch",
      read: false,
      at: ago(0.3),
      deliverableId: "deliverable_gym_launch",
    },
    {
      to: "user_dev",
      type: "APPROVED",
      title: "Founder Portrait Set passed internal review",
      message: "Manas approved your retouch pass.",
      url: "/agency/deliverables/deliverable_founder_portrait",
      read: false,
      at: ago(2),
      deliverableId: "deliverable_founder_portrait",
    },
  ];
  await db.insert(notifications).values(
    notify.map((n, i) => ({
      id: `demo_n_${i}`,
      agencyId: AGENCY,
      recipientUserId: n.to,
      sourceEventId: `demo_n_src_${i}`,
      type: n.type as never,
      title: n.title,
      message: n.message,
      url: n.url,
      relatedProjectId: n.projectId ?? null,
      relatedDeliverableId: n.deliverableId ?? null,
      isRead: n.read,
      readAt: n.read ? n.at : null,
      createdAt: n.at,
    })),
  );

  // ----------------------------------------------------------- automations
  await db.insert(rules).values([
    {
      id: "demo_r_1",
      agencyId: AGENCY,
      name: "Notify the lead when a version lands",
      kind: "RULE",
      enabled: true,
      scope: "AGENCY",
      trigger: { event: "VERSION_UPLOADED" },
      conditions: { contentType: "MOTION" },
      actions: [{ type: "NOTIFY", target: "PROJECT_LEAD" }],
    },
    {
      id: "demo_r_2",
      agencyId: AGENCY,
      name: "Auto-assign statics to Neha",
      kind: "RULE",
      enabled: true,
      scope: "PROJECT",
      scopeId: "project_june_retainer",
      trigger: { event: "DELIVERABLE_CREATED" },
      conditions: { contentType: "STATIC" },
      actions: [{ type: "ASSIGN", userId: "user_neha" }],
    },
    {
      id: "demo_r_3",
      agencyId: AGENCY,
      name: "Send to client review",
      kind: "CARD_BUTTON",
      enabled: true,
      scope: "AGENCY",
      trigger: { button: "send_to_client" },
      conditions: {},
      actions: [{ type: "SET_STATUS", status: "UNDER_CLIENT_REVIEW" }],
    },
    {
      id: "demo_r_4",
      agencyId: AGENCY,
      name: "Archive everything approved over 90 days ago",
      kind: "SCHEDULED",
      enabled: false,
      scope: "AGENCY",
      trigger: { cron: "0 3 * * 1" },
      conditions: { status: "APPROVED", olderThanDays: 90 },
      actions: [{ type: "SET_STATUS", status: "ARCHIVED" }],
    },
    {
      id: "demo_r_5",
      agencyId: AGENCY,
      name: "Nudge two days before the due date",
      kind: "DUE_DATE",
      enabled: true,
      scope: "AGENCY",
      trigger: { offsetDays: -2 },
      conditions: {},
      actions: [{ type: "NOTIFY", target: "ASSIGNEE" }],
    },
    {
      id: "demo_r_6",
      agencyId: AGENCY,
      name: "Sweep the board into delivered",
      kind: "BOARD_BUTTON",
      enabled: false,
      scope: "PROJECT",
      scopeId: "project_q3_launch",
      trigger: { button: "sweep_delivered" },
      conditions: { status: "APPROVED" },
      actions: [{ type: "SET_STATUS", status: "DELIVERED" }],
    },
  ]);

  await db.insert(intakeForms).values({
    id: "demo_form_brief",
    agencyId: AGENCY,
    name: "New campaign brief",
    slug: "new-campaign",
    targetConfig: { clientId: "client_imperial", projectType: "Campaign" },
  });
  await db.insert(formFields).values([
    {
      agencyId: AGENCY,
      formId: "demo_form_brief",
      key: "campaign_name",
      label: "Campaign name",
      type: "TEXT",
      required: true,
      position: 0,
    },
    {
      agencyId: AGENCY,
      formId: "demo_form_brief",
      key: "launch_date",
      label: "Launch date",
      type: "DATE",
      required: true,
      position: 1,
    },
    {
      agencyId: AGENCY,
      formId: "demo_form_brief",
      key: "channels",
      label: "Channels",
      type: "MULTI_SELECT",
      required: false,
      position: 2,
    },
    {
      agencyId: AGENCY,
      formId: "demo_form_brief",
      key: "budget",
      label: "Budget (INR)",
      type: "NUMBER",
      required: false,
      position: 3,
    },
    {
      agencyId: AGENCY,
      formId: "demo_form_brief",
      key: "rush",
      label: "Rush job?",
      type: "BOOLEAN",
      required: false,
      position: 4,
    },
  ]);
  await db.insert(formSubmissions).values([
    {
      agencyId: AGENCY,
      formId: "demo_form_brief",
      answers: { campaign_name: "Q4 Membership Push", channels: ["IG", "YT"], rush: false },
      status: "PROVISIONED",
      createdProjectId: "project_nova_draft",
      createdAt: ago(6),
    },
    {
      agencyId: AGENCY,
      formId: "demo_form_brief",
      answers: { campaign_name: "Winter capsule", budget: 450000, rush: true },
      status: "QUEUED",
      createdAt: ago(1),
    },
    {
      agencyId: AGENCY,
      formId: "demo_form_brief",
      answers: { campaign_name: "test test", rush: true },
      status: "REJECTED",
      createdAt: ago(3),
    },
  ]);

  await db.insert(templatePacks).values([
    {
      id: "demo_tp_retainer",
      agencyId: AGENCY,
      name: "Monthly social retainer",
      description: "12 reels + 16 statics, two sub-projects, default pipeline.",
      payload: { reels: 12, statics: 16 },
    },
    {
      id: "demo_tp_launch",
      agencyId: AGENCY,
      name: "Campaign launch",
      description: "Hero film, brand board, deck.",
      payload: { deliverables: 3 },
    },
  ]);
  await db.insert(recurringSchedules).values([
    {
      agencyId: AGENCY,
      scope: "PROJECT",
      templatePackId: "demo_tp_retainer",
      sourceProjectId: "project_june_retainer",
      cadence: "monthly:1",
      mode: "TIME_DRIVEN",
      nextRunAt: ahead(9),
      lastRunAt: ago(21),
      enabled: true,
    },
    {
      agencyId: AGENCY,
      scope: "DELIVERABLE",
      sourceProjectId: "project_nova_launch",
      cadence: "weekly:mon",
      mode: "COMPLETION_DRIVEN",
      nextRunAt: ahead(2),
      enabled: false,
    },
  ]);

  // -------------------------------------------------------- fields & views
  const fieldDefs = [
    { id: "demo_fd_content", key: "content_type", label: "Content Type", type: "SINGLE_SELECT" },
    { id: "demo_fd_platform", key: "platform", label: "Platform", type: "SINGLE_SELECT" },
    { id: "demo_fd_aspect", key: "aspect_ratio", label: "Aspect Ratio", type: "SINGLE_SELECT" },
    { id: "demo_fd_campaign", key: "campaign", label: "Campaign", type: "TEXT" },
  ] as const;
  await db.insert(customFieldDefs).values(
    fieldDefs.map((f, position) => ({
      id: f.id,
      agencyId: AGENCY,
      scope: "DELIVERABLE" as const,
      key: f.key,
      label: f.label,
      type: f.type as never,
      options:
        f.key === "platform"
          ? ["Instagram", "YouTube", "LinkedIn"]
          : f.key === "aspect_ratio"
            ? ["9:16", "1:1", "4:5", "16:9"]
            : f.key === "content_type"
              ? ["Reel", "Carousel", "Static", "Film"]
              : null,
      groupable: true,
      isBuiltIn: true,
      position,
    })),
  );
  await db.insert(customFieldValues).values([
    {
      agencyId: AGENCY,
      fieldDefId: "demo_fd_platform",
      entityType: "DELIVERABLE",
      entityId: "deliverable_beach_vibe",
      value: "Instagram",
    },
    {
      agencyId: AGENCY,
      fieldDefId: "demo_fd_aspect",
      entityType: "DELIVERABLE",
      entityId: "deliverable_beach_vibe",
      value: "9:16",
    },
    {
      agencyId: AGENCY,
      fieldDefId: "demo_fd_campaign",
      entityType: "DELIVERABLE",
      entityId: "deliverable_beach_vibe",
      value: "June drop",
    },
    {
      agencyId: AGENCY,
      fieldDefId: "demo_fd_platform",
      entityType: "DELIVERABLE",
      entityId: "deliverable_gym_launch",
      value: "Instagram",
    },
    {
      agencyId: AGENCY,
      fieldDefId: "demo_fd_aspect",
      entityType: "DELIVERABLE",
      entityId: "deliverable_gym_launch",
      value: "9:16",
    },
  ]);
  await db.insert(savedViews).values([
    {
      agencyId: AGENCY,
      ownerUserId: "user_manas",
      scope: "GLOBAL",
      name: "Everything urgent",
      viewType: "LIST",
      filterJson: { priority: ["URGENT", "HIGH"] },
      sortJson: { dueDate: "asc" },
      isShared: true,
      position: 0,
    },
    {
      agencyId: AGENCY,
      ownerUserId: "user_manas",
      scope: "PROJECT",
      scopeId: "project_june_retainer",
      name: "Retainer board",
      viewType: "BOARD",
      groupBy: "status",
      isShared: true,
      position: 1,
    },
    {
      agencyId: AGENCY,
      ownerUserId: "user_riya",
      scope: "MY_WORK",
      name: "My reels this week",
      viewType: "CALENDAR",
      filterJson: { assignedToUserId: "user_riya", contentType: "MOTION" },
      position: 0,
    },
    {
      agencyId: AGENCY,
      ownerUserId: "user_arjun",
      scope: "GLOBAL",
      name: "Q3 timeline",
      viewType: "TIMELINE",
      filterJson: { projectId: "project_q3_launch" },
      isShared: true,
      position: 2,
    },
  ]);

  // ------------------------------------------------- uploads & attachments
  await db.insert(uploadSessions).values([
    {
      agencyId: AGENCY,
      deliverableId: "deliverable_nova_statics",
      purpose: "VERSION",
      uploadKey: "demo/upload/init",
      bytesTotal: BigInt(120 * 1024 ** 2),
      status: "INIT",
      expiresAt: ahead(1),
      createdByUserId: "user_neha",
    },
    {
      agencyId: AGENCY,
      deliverableId: "deliverable_beach_vibe",
      purpose: "VERSION",
      uploadKey: "demo/upload/uploading",
      bytesTotal: BigInt(640 * 1024 ** 2),
      bytesUploaded: BigInt(288 * 1024 ** 2),
      status: "UPLOADING",
      expiresAt: ahead(1),
      createdByUserId: "user_riya",
    },
    {
      agencyId: AGENCY,
      deliverableId: "deliverable_gym_launch",
      purpose: "COMPANION_PREVIEW",
      targetVersionId: "fv_gym_v1",
      uploadKey: "demo/upload/complete",
      bytesTotal: BigInt(88 * 1024 ** 2),
      bytesUploaded: BigInt(88 * 1024 ** 2),
      status: "COMPLETE",
      completedAt: ago(1),
      expiresAt: ago(0.5),
      createdByUserId: "user_riya",
    },
    {
      agencyId: AGENCY,
      deliverableId: "deliverable_holiday_teaser",
      purpose: "VERSION",
      uploadKey: "demo/upload/aborted",
      bytesTotal: BigInt(300 * 1024 ** 2),
      bytesUploaded: BigInt(12 * 1024 ** 2),
      status: "ABORTED",
      expiresAt: ago(2),
      createdByUserId: "user_riya",
    },
    {
      agencyId: AGENCY,
      deliverableId: "deliverable_menu_static",
      purpose: "ATTACHMENT",
      uploadKey: "demo/upload/expired",
      bytesTotal: BigInt(4 * 1024 ** 2),
      status: "EXPIRED",
      expiresAt: ago(6),
      createdByUserId: "user_neha",
    },
  ]);
  await db.insert(attachments).values([
    {
      agencyId: AGENCY,
      objectKey: "demo/attachments/reference-board.jpg",
      uploadId: "demo-att-1",
      fileName: "reference-board.jpg",
      fileType: "image/jpeg",
      fileSizeBytes: BigInt(2 * 1024 ** 2),
      status: "CLAIMED",
      ownerUserId: "user_manas",
      parentType: "COMMENT",
      parentId: "demo_c_board_1",
      expiresAt: ahead(30),
      claimedAt: ago(0.9),
    },
    {
      agencyId: AGENCY,
      objectKey: "demo/attachments/licence.pdf",
      uploadId: "demo-att-2",
      fileName: "music-licence.pdf",
      fileType: "application/pdf",
      fileSizeBytes: BigInt(320 * 1024),
      status: "READY",
      ownerUserId: "user_tara",
      expiresAt: ahead(3),
    },
    {
      agencyId: AGENCY,
      objectKey: "demo/attachments/pending.png",
      uploadId: "demo-att-3",
      fileName: "wip-screenshot.png",
      fileType: "image/png",
      fileSizeBytes: BigInt(880 * 1024),
      status: "PENDING",
      ownerUserId: "user_riya",
      expiresAt: ahead(1),
    },
  ]);

  // ------------------------------------------------------------ audit logs
  const audits: Array<[string, string, string, string, Date]> = [
    ["user_manas", "team.invite", "USER", "user_dev", ago(30)],
    ["user_manas", "team.suspend", "USER", "user_vikram", ago(8)],
    ["user_arjun", "project.create", "PROJECT", "project_nova_launch", ago(11)],
    ["user_tara", "share.create", "SHARE", "demo_sh_gym", ago(1)],
    ["user_sara", "approval.sign", "DELIVERABLE", "deliverable_q3_deck", ago(5)],
    ["user_manas", "client.archive", "CLIENT", "client_harbour", ago(120)],
    ["user_arjun", "automation.disable", "RULE", "demo_r_4", ago(2)],
  ];
  await db.insert(auditLogs).values(
    audits.map(([actor, action, targetType, targetId, createdAt]) => ({
      agencyId: AGENCY,
      actorUserId: actor,
      action,
      targetType,
      targetId,
      meta: {},
      ip: "203.0.113.7",
      createdAt,
    })),
  );

  // ------------------------------------------------------------- passwords
  const password = await hashPassword(PASSWORD);
  await db.insert(accounts).values(
    ownedUsers.map((userId) => ({
      id: `demo_acct_${userId}`,
      accountId: userId,
      providerId: "credential",
      userId,
      password,
      updatedAt: new Date(),
    })),
  );

  // The super admin and the cross-tenant "outsider" live outside this agency, so the
  // wipe above never touches them — but they still need a password to sign in with.
  for (const userId of ["user_root", "user_outsider"]) {
    const exists = await db.execute(raw`select 1 from "user" where id = ${userId}`);
    if (exists.length === 0) continue;
    await db
      .insert(accounts)
      .values({
        id: `demo_acct_${userId}`,
        accountId: userId,
        providerId: "credential",
        userId,
        password,
        updatedAt: new Date(),
      })
      .onConflictDoUpdate({ target: accounts.id, set: { password, updatedAt: new Date() } });
  }

  const counted = await db.execute(raw`
    select
      (select count(*) from "user" where agency_id = ${AGENCY}) as users,
      (select count(*) from client where agency_id = ${AGENCY}) as clients,
      (select count(*) from project where agency_id = ${AGENCY}) as projects,
      (select count(*) from deliverable where agency_id = ${AGENCY}) as deliverables,
      (select count(*) from file_version where agency_id = ${AGENCY}) as versions,
      (select count(*) from comment where agency_id = ${AGENCY}) as comments,
      (select count(*) from notification where agency_id = ${AGENCY}) as notifications
  `);
  console.log("Demo dataset seeded:", counted[0]);
  console.log(`All demo accounts use the password: ${PASSWORD}`);
}

seed()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(() => sql.end());

void inArray;
void ownedProjects;
void ownedDeliverables;
void ownedClients;
