export type FileVersionView = {
  id: string;
  versionNumber: number;
  majorVersion: number;
  minorVersion: number;
  displayVersion: string;
  versionBump: "MAJOR" | "MINOR";
  label: string | null;
  tags: string[];
  isMinor: boolean;
  fileName: string | null;
  fileType: string | null;
  fileSizeBytes?: string | null;
  isSource?: boolean;
  previewUrl: string | null;
  previewStatus: "PENDING" | "PROCESSING" | "READY" | "FAILED";
  previewError?: string | null;
  posterFrameUrl?: string | null;
  thumbnailSpriteUrl?: string | null;
  spriteIntervalMs?: number | null;
  spriteColumns?: number | null;
  spriteRows?: number | null;
  spriteCellWidth?: number | null;
  spriteCellHeight?: number | null;
  durationMs?: number | null;
  externalLink: string | null;
  visibility: string;
  status: string;
  createdAt?: string;
};
